// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_amdBigMatrix_daxpy
void cpp_amdBigMatrix_daxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdBigMatrix_daxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    cpp_amdBigMatrix_daxpy(alpha_, A_, B_);
    return R_NilValue;
END_RCPP
}
// cpp_amdBigMatrix_dgemm
void cpp_amdBigMatrix_dgemm(SEXP A_, SEXP B_, SEXP C_);
RcppExport SEXP gpuRclblas_cpp_amdBigMatrix_dgemm(SEXP A_SEXP, SEXP B_SEXP, SEXP C_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type C_(C_SEXP);
    cpp_amdBigMatrix_dgemm(A_, B_, C_);
    return R_NilValue;
END_RCPP
}
// cpp_amdBigMatrix_saxpy
void cpp_amdBigMatrix_saxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdBigMatrix_saxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    cpp_amdBigMatrix_saxpy(alpha_, A_, B_);
    return R_NilValue;
END_RCPP
}
// cpp_amdBigMatrix_sgemm
void cpp_amdBigMatrix_sgemm(SEXP A_, SEXP B_, SEXP C_);
RcppExport SEXP gpuRclblas_cpp_amdBigMatrix_sgemm(SEXP A_SEXP, SEXP B_SEXP, SEXP C_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type C_(C_SEXP);
    cpp_amdBigMatrix_sgemm(A_, B_, C_);
    return R_NilValue;
END_RCPP
}
// cpp_amdMatrix_daxpy
SEXP cpp_amdMatrix_daxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_daxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_amdMatrix_daxpy(alpha_, A_, B_));
    return __result;
END_RCPP
}
// cpp_amdMatrix_dgemm
SEXP cpp_amdMatrix_dgemm(SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_dgemm(SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_amdMatrix_dgemm(A_, B_));
    return __result;
END_RCPP
}
// cpp_amdMatrix_saxpy
SEXP cpp_amdMatrix_saxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_saxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_amdMatrix_saxpy(alpha_, A_, B_));
    return __result;
END_RCPP
}
// cpp_amdMatrix_sgemm
SEXP cpp_amdMatrix_sgemm(SEXP A_, SEXP B_);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_sgemm(SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_amdMatrix_sgemm(A_, B_));
    return __result;
END_RCPP
}
