// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_amdMatrix_axpy
void cpp_amdMatrix_axpy(SEXP alpha, SEXP ptrA, SEXP ptrB, const int type_flag, int ctx_id);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_axpy(SEXP alphaSEXP, SEXP ptrASEXP, SEXP ptrBSEXP, SEXP type_flagSEXP, SEXP ctx_idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrA(ptrASEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrB(ptrBSEXP);
    Rcpp::traits::input_parameter< const int >::type type_flag(type_flagSEXP);
    Rcpp::traits::input_parameter< int >::type ctx_id(ctx_idSEXP);
    cpp_amdMatrix_axpy(alpha, ptrA, ptrB, type_flag, ctx_id);
    return R_NilValue;
END_RCPP
}
// cpp_amdMatrix_gemm
void cpp_amdMatrix_gemm(SEXP ptrA, SEXP ptrB, SEXP ptrC, const int type_flag, int ctx_id);
RcppExport SEXP gpuRclblas_cpp_amdMatrix_gemm(SEXP ptrASEXP, SEXP ptrBSEXP, SEXP ptrCSEXP, SEXP type_flagSEXP, SEXP ctx_idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type ptrA(ptrASEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrB(ptrBSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptrC(ptrCSEXP);
    Rcpp::traits::input_parameter< const int >::type type_flag(type_flagSEXP);
    Rcpp::traits::input_parameter< int >::type ctx_id(ctx_idSEXP);
    cpp_amdMatrix_gemm(ptrA, ptrB, ptrC, type_flag, ctx_id);
    return R_NilValue;
END_RCPP
}
