# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_amdMatrix_axpy <- function(alpha, ptrA, ptrB, type_flag, ctx_id) {
    invisible(.Call('gpuRclblas_cpp_amdMatrix_axpy', PACKAGE = 'gpuRclblas', alpha, ptrA, ptrB, type_flag, ctx_id))
}

cpp_amdMatrix_gemm <- function(ptrA, ptrB, ptrC, type_flag, ctx_id) {
    invisible(.Call('gpuRclblas_cpp_amdMatrix_gemm', PACKAGE = 'gpuRclblas', ptrA, ptrB, ptrC, type_flag, ctx_id))
}

