# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_amdBigMatrix_daxpy <- function(alpha_, A_, B_) {
    invisible(.Call('gpuRclblas_cpp_amdBigMatrix_daxpy', PACKAGE = 'gpuRclblas', alpha_, A_, B_))
}

cpp_amdBigMatrix_dgemm <- function(A_, B_, C_) {
    invisible(.Call('gpuRclblas_cpp_amdBigMatrix_dgemm', PACKAGE = 'gpuRclblas', A_, B_, C_))
}

cpp_amdBigMatrix_saxpy <- function(alpha_, A_, B_) {
    invisible(.Call('gpuRclblas_cpp_amdBigMatrix_saxpy', PACKAGE = 'gpuRclblas', alpha_, A_, B_))
}

cpp_amdBigMatrix_sgemm <- function(A_, B_, C_) {
    invisible(.Call('gpuRclblas_cpp_amdBigMatrix_sgemm', PACKAGE = 'gpuRclblas', A_, B_, C_))
}

cpp_amdMatrix_daxpy <- function(alpha_, A_, B_) {
    .Call('gpuRclblas_cpp_amdMatrix_daxpy', PACKAGE = 'gpuRclblas', alpha_, A_, B_)
}

cpp_amdMatrix_dgemm <- function(A_, B_) {
    .Call('gpuRclblas_cpp_amdMatrix_dgemm', PACKAGE = 'gpuRclblas', A_, B_)
}

cpp_amdMatrix_saxpy <- function(alpha_, A_, B_) {
    .Call('gpuRclblas_cpp_amdMatrix_saxpy', PACKAGE = 'gpuRclblas', alpha_, A_, B_)
}

cpp_amdMatrix_sgemm <- function(A_, B_) {
    .Call('gpuRclblas_cpp_amdMatrix_sgemm', PACKAGE = 'gpuRclblas', A_, B_)
}

